spring:
  config:
    activate:
      on-profile: %1$s
  %3$s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    net.jlstechnology: DEBUG
%4$s
