spring:
  config:
    activate:
      on-profile: %1$s
  datasource:
    url: jdbc:postgresql://localhost:5432/%2$s
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    net.jlstechnology: DEBUG

